### ISSUE TITLE
Fail to upload to s3 with HandshakeException.

### ISSUE THREAD

**Issue by Kakukaho** [Serdnad/aws_s3_upload#10]
I[/flutter]() (31849): Failed to upload to AWS, with exception:
I[/flutter]() (31849): HandshakeException: Handshake error in client (OS Error:
I[/flutter]() (31849): 	CERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:359))

**Comment by Serdnad** [comment]
Should be fixed by https://github.com/Serdnad/aws_s3_upload/pull/11
