### ISSUE TITLE
SocketException: OS Error: Broken pipe, errno = 32, address = jewtube-source-14c5ef0ws4cpc.s3-us-west-2.amazonaws.com, port = 33492

### ISSUE THREAD

**Issue by abdullah432** [Serdnad/aws_s3_upload#2]
I'm getting following issue when trying to upload a file

SocketException: OS Error: Broken pipe, errno = 32, address = jewtube-source-14c5ef0ws4cpc.s3-us-west-2.amazonaws.com, port = 33492

**Comment by gbeiduofen** [comment]
me to

**Comment by abdullah432** [comment]
It was due to wrong keys, after updating keys, it's now working fine.
