### ISSUE TITLE
Specify Content-type for viewable Images?

### ISSUE THREAD

**Issue by meghead** [Serdnad/aws_s3_upload#3]
Is it possible to specify the Content-type metadata for images? Currently, clicking the Object URL downloads the image instead of displaying it in the browser. By default, it seems to upload to the S3 bucket as a "binary/octet-stream" instead of "image/jpg".

**Comment by Serdnad** [comment]
Good catch. It seems like Content-Type can be included in the request body, similar to [here](https://stackoverflow.com/a/29656722/2330228).

I'm not able to work on this right atm, but PRs are welcome.

**Comment by clozed2u** [comment]
@Serdnad @meghead I faced this same problem, so I created #13 to fix the issue.
