### ISSUE TITLE
Aws Value Null with broken pipe

### ISSUE THREAD

**Issue by AimanKyo97** [Serdnad/aws_s3_upload#7]
I have run the package with all the info but the logs say :

flutter: Aws has running
flutter: Aws value : null
flutter: Failed to upload to AWS, with exception:
flutter: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = kantact-private.s3-ap-southeast-1.amazonaws.com, port = 53181

Whats is wrong here?

**Comment by jasonroland** [comment]
Very possible you are uploading to a private bucket (the default on AWS)

This plug-in currently uploads the file as public-read so if your bucket is private and you try to upload a file with public-read acl you will get that error. 

I have submitted a PR that can let you choose what permissions you want.

**Comment by AimanKyo97** [comment]
@jasonroland i see,when it can be merged to main branch?

**Comment by jasonroland** [comment]
I originally created a PR that wasn't uploaded correctly and was missing some files, I just reuploaded and created a new PR, this repo is being maintained and I have been in contact with Serdnad, I am confident that he will review and publish.

**Comment by jasonroland** [comment]
Looks like @Serdnad has not been answering, feel free to try out the PR by downloading it, you can also look at the changes made and implement yourself. If this repo is not being maintained then I will have to post my own as there are more updates im looking to make like displaying progress on uploads.

**Comment by Serdnad** [comment]
I apologize for the silence, I haven't touched Flutter in a while and hadn't had time to follow this. I've merged both @jasonroland 's MR and also https://github.com/Serdnad/aws_s3_upload/pull/11. I suspect at least one of those changes should have fixed this issue.
