### ISSUE TITLE
Failed to upload to AWS, with exception

### ISSUE THREAD

**Issue by hasnainelahi** [Serdnad/aws_s3_upload#9]
package version: aws_s3_upload: ^1.2.0
Failed to upload to AWS, with exception:
SocketException: Failed host lookup: 'bucket-name.s3-us-east-1.amazonaws.com' (OS Error: No address associated with hostname, errno = 7)

- my endpoint in the package file:    final endpoint = 'https://$bucket.s3-$region.amazonaws.com';

-AndroidManifest.xml : <uses-permission android:name="android.permission.INTERNET"/>

anyone can help me? how to solve!

**Comment by jasonroland** [comment]
hey how are you, it may be related to an issue I'm solving. (maybe not) can you tell me what the ACL permissions of your was bucket are. 

Does your bucket block all public read/write access?

**Comment by Serdnad** [comment]
Should be fixed by https://github.com/Serdnad/aws_s3_upload/pull/11
